services:
  db1:
    image: mariadb:10.11
    container_name: db1
    hostname: db1
    restart: always
    command: --server-id=1 --log-bin --log-slave-updates --log-basename=mariadb --performance-schema=1 --userstat=1
    environment:
      - MARIADB_ROOT_PASSWORD=dba
      - MARIADB_REPLICATION_USER=repl
      - MARIADB_REPLICATION_PASSWORD=repl
    ports:
      - 3307:3306
    volumes:
      - ${PWD}/setup:/docker-entrypoint-initdb.d

  db2:
    image: mariadb:10.11
    container_name: db2
    hostname: db2
    restart: always
    command: --server-id=2 --log-bin --log-slave-updates --log-basename=mariadb --read-only --performance-schema=1 --userstat=1
    environment:
      - MARIADB_ROOT_PASSWORD=dba
      - MARIADB_REPLICATION_USER=repl
      - MARIADB_REPLICATION_PASSWORD=repl
      - MARIADB_MASTER_HOST=db1
    ports:
      - 3308:3306
    volumes:
      - ${PWD}/setup:/docker-entrypoint-initdb.d

  pmm:
    image: percona/pmm-server
    container_name: pmm
    hostname: pmm
    ports:
      - 443:443
